name: hamnt
version: '0.3.0'
summary: Hyper Aggressively Minimal Note Taking CLI
description: |
  CLI and interactive shell app for rapid note taking across multiple files.
  Allows quick access to notes via aliases regardless of their location.

base: core22
confinement: strict
grade: stable

apps:
  hamnt:
    command: bin/hamnt
    plugs:
      - home
      - network
    environment:
      DOTNET_BUNDLE_EXTRACT_BASE_DIR: $SNAP_USER_COMMON/dotnet_extract

plugs:
  
parts:
  hamnt:
    plugin: dump
    source: ./bin/Release/net8.0/linux-x64/publish/
    organize:
      "hamnt": bin/hamnt